apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      containers:
        - name: ngrok
          image: ngrok/ngrok
          env:
            - name: NGROK_AUTHTOKEN
              value: "2v3DQGw6dxTNMJtHBNRmgJI2Oqa_4NUZUj8t6zfhSz4UsB5Ae"  # Replace with your actual token
            - name: NGROK_REGION
              value: "us"
          args:
            - "http"
            - "gitea-http.default.svc.cluster.local:3000"  # Gitea service in your cluster
